### ISSUE TITLE
Error parsing %s%s

### ISSUE THREAD

**Issue by watson** [davidmarkclements/quick-format-unescaped#18]
If two `%s` is next to each other, the last one will be ignored:

```js
var format = require('quick-format-unescaped')
format('%s%s', 'foo', 'bar') // => "foo%s bar"
format('%s %s', 'foo', 'bar') // => "foo bar"
```

**Comment by davidmarkclements** [comment]
Hahaha .. woops 

It's going to take me a week and a half to get to this - but in the meantime pr's welcome - also maybe @mcollina do you have bandwidth?

**Comment by mcollina** [comment]
I would say fix the tests first.

We should really restructure this module so that we don't publish two modules from two branches, and the tests are verified by Travis.

I'm currently tied up for the next two weeks I'm afraid.

**Comment by watson** [comment]
> I would say fix the tests first.

I would normally have done that, but I didn't have time. Hence I created this issue so the bug at least was reported as I didn't feel comfortable fixing this without a passing test suite.

**Comment by mcollina** [comment]
Tests are now passing @watson!
