### ISSUE TITLE
Update fast-safe-stringify?

### ISSUE THREAD

**Issue by daveisfera** [davidmarkclements/quick-format-unescaped#26]
`fast-safe-stringify` is now on 2.0.7 and it would be nice to update to use it

**Comment by jsumners** [comment]
This does not depend on `fast-safe-stringify`. Am I missing something?

**Comment by daveisfera** [comment]
It used to but apparently that dependency has been removed:
https://github.com/davidmarkclements/quick-format-unescaped/commit/cad2849a129fa57bd92e4ba316479aeabc1f6eb6#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L17
