### ISSUE TITLE
unsupported %f and %i replacements

### ISSUE THREAD

**Issue by commenthol** [davidmarkclements/quick-format-unescaped#31]
console.log offers %f and %i as replacements which are unsupported by this package.
%f is an alternative to %d where %i floors the numeric value.

e.g.
```js
console.log('%f', 42.9) //> 42.9
console.log('%i', 42.9) //> 42
```

Is it a goal of this lib to support those replacements?

**Comment by mcollina** [comment]
I would say so! Would you like to send a PR?

**Comment by commenthol** [comment]
Thanks for the quick response. Yes will do.

**Comment by commenthol** [comment]
Thanks for merging
